services:
  restaurante:
    build:
      context: .
      dockerfile: Dockerfile
    image: restaurante-frontend:latest
    container_name: Restaurante-Frontend
    restart: unless-stopped
    ports:
      - "5015:80"
    networks:
      - restaurante-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  restaurante-network:
    driver: bridge